apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME.git' # UPDATE THIS
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
